### ISSUE TITLE
1.0.0版本sdkCAN例程bug

### ISSUE THREAD

**Issue by kvvipa0028** [hpmicro/hpm_sdk#10]
1. board_can_send_multiple_messages里     tx_buf.dlc = 8; 书写错误 应为can_payload_size_8 ; 其他几个测试demo也类似的问题
2. hpm_can_drv.h里can_read_received_message 无法读空接收buffer. 会造成数据积压在缓冲区. 不建议在中断里配合CAN_EVENT_RECEIVE标志使用; 如果使用需要判断buff是否读空了. 否则建议使用can_receive_message_blocking

**Comment by helloeagleyang** [comment]
您好，感谢反馈：
对于问题1.  dlc的赋值既可以用数字，也可以用(uint32_t) can_playload_size_8这种表达式，效果都是一样的。定义can_playload_size_<x>这种枚举变量的本意是为了CAN-FD的使用场景下，发送和接收时对DLC的翻译能更易读，并不强制使用。

对于问题2.  该函数只是定义来读取当前FIFO的第一个元素，用户需要在明确知道FIFO中有数据的情况下调用。如果要读取FIFO中的所有帧，则需要配合判断Rcevie Buffer 的状态是否为空来实现，只要FIFO不为空，可以一直调用该API来读取。 例程中的中断里的代码是服务于示例的，只有结合示例来解读才最贴切。
