### ISSUE TITLE
hpm sdk什么时候适配nuttx

### ISSUE THREAD

**Issue by linhuikui** [hpmicro/hpm_sdk#11]
nuttx功能比较强大，有Linux特性，又是实时系统且占用资源少；hpm sdk何时适配nuttx系统？https://github.com/apache/nuttx

**Comment by linhuikui** [comment]
查看了一下，hpm6750有适配好了，那什么时候适配hpm6360呢？

**Comment by jhqian** [comment]
有的有的，不过bandwidth有限，一步步来。建议后面有nuttx的issue可以提交到我们nuttx repo
