### ISSUE TITLE
sm4 算法的速度

### ISSUE THREAD

**Issue by jorislee** [hpmicro/hpm_sdk#12]
测试 rom sm4  api 速度发现与软件计算的速度相差很小，芯片带的 sm4 只是内置一个软件函数，没有任何硬件加速吗？

**Comment by helloeagleyang** [comment]
请问是基于什么芯片测试的结果？

**Comment by jorislee** [comment]
HPM6750 芯片，HPM6750EVK2 开发板。

**Comment by jorislee** [comment]
测试方法: 100W次 16byte SM4 ECB 加密循环，计算耗时。

**Comment by helloeagleyang** [comment]
6750上是软件实现的

**Comment by jorislee** [comment]
根据您的这个反问，是有哪个型号硬件实现的吗？

**Comment by helloeagleyang** [comment]
您的理解是对的，HPM6200系列上带有硬件的SM3和SM4实现

**Comment by jorislee** [comment]
还有其他的型号是硬件吗？比如 HPM6400 系列，带有双路以太网。

**Comment by jorislee** [comment]
像是支持 sm4ed 与 sm4ks 指令加速也可以

**Comment by jorislee** [comment]
再或者有预期的未来芯片也行。

**Comment by jorislee** [comment]
再或者有预期的未来芯片也行。

**Comment by helloeagleyang** [comment]
> 还有其他的型号是硬件吗？比如 HPM6400 系列，带有双路以太网。

目前只有HPM6200系列带硬件SM3/4，后续芯片的信息请咨询先楫市场和销售。
