### ISSUE TITLE
HPM6750 SDK did not support disable compress instruction

### ISSUE THREAD

**Issue by wjzhang** [hpmicro/hpm_sdk#18]
Hi : 
    i did not want program generate 16bit compress instruction,  change the ARCH to the "rv32ima". use gcc toolchain.
    But found the SDK_DECLARE_EXT_ISR_M use Assembler 16 bit instruction doing optimization in board.c.
    why did not add Assembler 32 bit instruction optimization? 

SDK version: 1.2.0
Board: hpm6750evkmini.
toolchain: rv32imac-ilp32-multilib-win

**Comment by helloeagleyang** [comment]
The 16-bit compression instruction is must-have for now to save code size. The SoC supports the compression instruction. This is no reason for SDK not to use it given the benefit is obvious.

Is there any special reason for you not to use it?

> Hi : i did not want program generate 16bit compress instruction, change the ARCH to the "rv32ima". use gcc toolchain. But found the SDK_DECLARE_EXT_ISR_M use Assembler 16 bit instruction doing optimization in board.c. why did not add Assembler 32 bit instruction optimization?
> 
> SDK version: 1.2.0 Board: hpm6750evkmini. toolchain: rv32imac-ilp32-multilib-win

**Comment by wjzhang** [comment]
No. just be curious.
Do 先楫半导体 consider support third party toolchain ? maybe use difference RISC-V Core for HPM6750 SDK compatibility in future?

**Comment by helloeagleyang** [comment]
> No. just be curious. Do 先楫半导体 consider support third party toolchain ? maybe use difference RISC-V Core for HPM6750 SDK compatibility in future?

Segger Embedded Studio for RISC-V is supported.
IAR for RISC-V is on the roadmap.

RISC-V core on HPM6750 can no longer be changed.
