### ISSUE TITLE
关于RGMII的描述

### ISSUE THREAD

**Issue by kylongmu** [hpmicro/hpm_sdk#2]
手册里面是这么描述的：拨码开关的第 3 位是用来选择对应 IO 是当千兆网接口或电机接口。当拨到 ON 档，对应引脚是选择板上 PWM输出，当拨到 OFF 档，对应引脚是选择板上千兆网接口。
而在开发板正对SW1的丝印层上，左上角是“1”，左下角是“RGMII”，与手册描述相反。

**Comment by jhqian** [comment]
有两个版本的evk，最初的版本丝印是反的，这已经在第二版的evk上fix，谢谢
