### ISSUE TITLE
some typing error in hpm_pwm_drv.c and hpm_pwm_drv.h

### ISSUE THREAD

**Issue by leonli8012** [hpmicro/hpm_sdk#3]
in hpm_pwm_drv.h line 696:  the function "void pwm_get_captured_count(..."
in hpm_pwm_drv.c line 24: the function "void  pwm_get_count(..."
I think they reffer to the same function, should be typing error, please check it

**Comment by willChuai** [comment]
hi, leonli8012

Thank you.
The above issue will be fixed in the next release.

**Comment by willChuai** [comment]
The above issue has been fixed in this [release v0.12.1](https://github.com/hpmicro/hpm_sdk/commit/8a1b57f498c37ecfafd14de7ea38424b07983fd2). I will close the issue.
