### ISSUE TITLE
定义在.fast_ram里的变量不会初始化

### ISSUE THREAD

**Issue by zyzyzyzzyy** [hpmicro/hpm_sdk#32]
使用  ATTR_PLACE_AT_WITH_ALIGNMENT(".fast_ram", 4)  int a=1;将变量存放在dlm ram里的时候，启动后变量a的值未能初始化。
使用sdk自带的工具链时会出现这个问题，SEGGER Embedded Studio for RISC-V 里不会出现。

应该是在reset.c里没有对应的初始化代码，.ld的链接文件里缺少对应的定义信息。

**Comment by jhqian** [comment]
谢谢，下个release fix
