### ISSUE TITLE
Linux 环境下的GCC编译器在哪里下载？

### ISSUE THREAD

**Issue by zhangshengping** [hpmicro/hpm_sdk#4]
在sdk_env_v0.12.1中没有看到Linux环境下的编译器。
请问Linux环境下的gcc编译器需要在哪里下载？

**Comment by jhqian** [comment]
https://github.com/hpmicro/riscv-gnu-toolchain

**Comment by zhangshengping** [comment]
谢谢您的回复，
再问一个弱智的问题。
需要什么样的配置选项来编译这个工具链呀？
我看readme里面没有写针对hpm6000的编译配置。

**Comment by jhqian** [comment]
我们准备了prebuilts https://github.com/hpmicro/riscv-gnu-toolchain/releases/tag/2022.05.15

**Comment by jhqian** [comment]
没有进一步问题就close了
