### ISSUE TITLE
Unable to parse SVD file

### ISSUE THREAD

**Issue by johnzhy** [hpmicro/hpm_sdk#45]
使用VSCode，仿真HPM5361，加载SVD文件出错，提示错误：
Unable to parse SVD file
********\sdk_env_v1.6.0\hpm_sdk/soc/HPM5300/HPM5361/HPM5361_svd.xml:
dimlndex Element has invalid specification.
但是复制sdk_env_v1.4.0里的svd文件覆盖后，加载正常

**Comment by quchao93** [comment]
Hi  你好， 可否提供提一下你在vscode中所使用的解析svd的插件
目前通过对比发现了sdk_env_v1.6.0中的svd存在一种问题， dim的count值小了， 小于<dimIndex>提供的index数目
但是我们使用的插件工具没报出这个问题。
方便的话， 麻烦帮忙验证一下更正的后的svd文件， 谢谢
[HPM5361_svd.zip](https://github.com/user-attachments/files/17055432/HPM5361_svd.zip)

**Comment by johnzhy** [comment]
更改后的svd文件可以正常解析了，我使用的插件是Cortex-Debug
