### ISSUE TITLE
先楫能否出一个ADC DMA连续采样的sample？

### ISSUE THREAD

**Issue by hexenzhou** [hpmicro/hpm_sdk#5]
看了一下sample目录里面没有adc的例子。

**Comment by jiadingxu** [comment]
你好，当前adc的示例在hpm_sdk\samples\drivers\adc目录下，有adc12和adc16。以sdk v0.13.0的ad12为例，若需要设置adc搭配DMA工作，可以把adc12.c中，357行的conv_mode赋值修改为adc12_conv_mode_sequence或者是adc12_conv_mode_preemption即可。

**Comment by jiadingxu** [comment]
![image](https://user-images.githubusercontent.com/57382671/195221384-3e1a7891-0e19-4652-98b9-eeb13e9f007e.png)

**Comment by jiadingxu** [comment]
> 看了一下sample目录里面没有adc的例子。

你好，当前adc的示例在hpm_sdk\samples\drivers\adc目录下，有adc12和adc16。以sdk v0.13.0的ad12为例，若需要设置adc搭配DMA工作，可以把adc12.c中，357行的conv_mode赋值修改为adc12_conv_mode_sequence或者是adc12_conv_mode_preemption即可。


> ![image](https://user-images.githubusercontent.com/57382671/195221384-3e1a7891-0e19-4652-98b9-eeb13e9f007e.png)

**Comment by jiadingxu** [comment]
> 看了一下sample目录里面没有adc的例子。

你好，当前adc的示例在hpm_sdk\samples\drivers\adc目录下，有adc12和adc16。以sdk v0.13.0的ad12为例，若需要设置adc搭配DMA工作，可以把adc12.c中，357行的conv_mode赋值修改为adc12_conv_mode_sequence或者是adc12_conv_mode_preemption即可。

![image](https://user-images.githubusercontent.com/57382671/195221948-52dda9b5-40bc-49ee-bf6d-1919250aab89.png)
