### ISSUE TITLE
是否考虑支持NuttX实时系统？

### ISSUE THREAD

**Issue by TompsonTan** [hpmicro/hpm_sdk#9]
无人机飞行控制系统，特别需要高性能的MCU。而例如开源的PX4飞控，主要基于Nuttx RTOS，现在STM32H7和NXP RT1060都支持了，希望也能支持Hpmicro的芯片，多一个国产选择。

**Comment by TompsonTan** [comment]
我看到已经有人提交Hpmicro的支持代码，不过他那个是直接把原版SDK包含进来，而NuttX的MCU BSP都是它自己的风格，相当于要重写，官方是否考虑做这块的支持？
https://github.com/apache/nuttx/pull/8411

**Comment by TompsonTan** [comment]
![图片](https://user-images.githubusercontent.com/3468649/216508509-d7ac925b-c5e2-4296-bd36-50203cdaed53.png)

**Comment by jhqian** [comment]
> 我看到已经有人提交Hpmicro的支持代码，不过他那个是直接把原版SDK包含进来，而NuttX的MCU BSP都是它自己的风格，相当于要重写，官方是否考虑做这块的支持？ [apache/nuttx#8411](https://github.com/apache/nuttx/pull/8411)
可以试一下我们的fork（https://github.com/hpmicro/nuttx/tree/hpmicro），从资源角度出发，我们暂时只会采用和SDK整合的方式提供支持
